// Setup Vars
var
	// Alias tasks only need to be registered once, so this is the only place we
	// call gulp/gulp-help like this.
	gulp   = require('gulp-help')(require('gulp'), { aliases: ['default', '?'] }),
	task   = require('./gulp/task');

// Run Bootstrap
require('./gulp/bootstrap')();

// Assign Tasks
gulp.task('build', 'Compile the source into a distribution.', task.build);
gulp.task('build-scripts', 'Compile, minify, and concat on-page scripting files.', task.buildScripts);
gulp.task('build-styles', 'Compile, minify, and concat stylesheets.', task.buildStyles);
gulp.task('build-docs', 'Copy docs generated by PHPDoc to asset folder.', task.buildDocs);
gulp.task('build-logo', 'Add logo to dist.', task.buildLogo);
gulp.task('build-readme', 'Generate HTML & PDF "README" from the project\'s README.md', task.buildReadme);
gulp.task('build-screenshot', 'Convert screenshot.svg into a PNG file.', task.buildScreenshot);
gulp.task('dep-check', 'Check all gulp dependencies.', task.depCheck);
gulp.task('fix-line-endings', 'Ensure all files have Unix EOLs.', task.fixLineEndings);
gulp.task('optimize-images', 'Attempt to reduce the size of all images.', task.optimizeImages);
gulp.task('test', 'Run The Unit Tests.', task.test);
gulp.task('version', 'Display the current version, copyright, and license info.', task.version);
gulp.task('watch', 'Continuously update the dist. directory when changes are made in the source directory.', task.watch);

// Assign Sub-Tasks
gulp.task('build/copy', false, task.build_copy);
gulp.task('build/remove-old', false, task.build_removeOld);
gulp.task('build-scripts/concat', false, task.buildScripts_concat);
gulp.task('build-scripts/copy', false, task.buildScripts_copy);
gulp.task('build-scripts/js', false, task.buildScripts_js);
gulp.task('build-scripts/minify', false, task.buildScripts_minify);
gulp.task('build-scripts/remove-old', false, task.buildScripts_removeOld);
gulp.task('build-styles/concat', false, task.buildStyles_concat);
gulp.task('build-styles/copy', false, task.buildStyles_copy);
gulp.task('build-styles/css', false, task.buildStyles_css);
gulp.task('build-styles/less', false, task.buildStyles_less);
gulp.task('build-styles/minify', false, task.buildStyles_minify);
gulp.task('build-styles/remove-old', false, task.buildStyles_removeOld);
gulp.task('build-styles/sass', false, task.buildStyles_sass);
