var gulp = require('gulp-help')(require('gulp'));

/**
 * Copy docs generated by PHPDoc to asset folder
 */
gulp.task('build-docs', 'Copy docs generated by PHPDoc to asset folder', function() {
	// Setup Vars
	var
		conf     = require('../config'),
		cli      = require('../cli'),
		fs = require("fs"),
		// Aliases
		build    = conf.build,
		paths    = build.paths;
	
	return gulp.src(cli.cwd + '/docs/**/*')
		.pipe(gulp.dest(paths.dist_styles + '/../docs'));
});
